#!/bin/bash
set -e
sudo apt install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
pushd gst-plugin
./autogen.sh
make
sudo make install
#export GST_PLUGIN_PATH=$(find /usr/local/lib/ -type d | grep gstreamer*)
popd
pushd gst-app
./autogen.sh
make
popd